const DB_NAME='wordflow-db', DB_VERSION=1, WORDS='words', META='meta';
const seed=[
  ['approachable','dễ gần','Appearance','B1','Her warm smile makes her look approachable.'],['of medium height','có chiều cao trung bình','Appearance','B1','He is of medium height.'],['an athletic build','vóc dáng thể thao','Appearance','B1','She has an athletic build.'],['a round face','khuôn mặt tròn','Appearance','A2','She has a round face.'],['expressive eyes','đôi mắt biểu cảm','Appearance','B1','He has warm, expressive eyes.'],['shoulder-length hair','tóc dài ngang vai','Appearance','B1','She has shoulder-length wavy hair.'],['well-groomed','chỉn chu','Appearance','B2','He always looks well-groomed.'],['sophisticated','tinh tế, trưởng thành','Appearance','B2','His outfit makes him look sophisticated.'],
  ['meet a deadline','kịp thời hạn','Work','B1','We need to meet the deadline.'],['take responsibility','chịu trách nhiệm','Work','B1','She takes responsibility for her work.'],['workload','khối lượng công việc','Work','B2','My workload has increased this month.'],['productive','năng suất','Work','B1','I am more productive in the morning.'],
  ['deploy a fix','triển khai bản sửa lỗi','Technology','B2','The team deployed a fix last night.'],['reproduce a bug','tái hiện lỗi','Technology','B2','The tester could not reproduce the bug.'],['user-friendly','thân thiện với người dùng','Technology','B1','The new interface is user-friendly.'],['data storage','lưu trữ dữ liệu','Technology','B1','Cloud data storage is convenient.'],
  ['anxious','lo lắng','Feelings','B1','I felt anxious before the interview.'],['delighted','rất vui mừng','Feelings','B1','She was delighted with the result.'],['upset','buồn và bực bội','Feelings','B1','He felt upset after the argument.'],['calm','bình tĩnh','Feelings','A2','She remained calm under pressure.']
];
let db,words=[],session=null,current=null,answerLocked=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;const ws=d.createObjectStore(WORDS,{keyPath:'id',autoIncrement:true});ws.createIndex('topic','topic');d.createObjectStore(META,{keyPath:'key'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function req(r){return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function load(){words=await req(tx(WORDS).getAll());if(!words.length){for(const [english,vietnamese,topic,level,example] of seed)await req(tx(WORDS,'readwrite').add({english,vietnamese,topic,level,example,mastered:false,correct:0,attempts:0,createdAt:Date.now()}));words=await req(tx(WORDS).getAll())}renderAll()}
function topics(){return [...new Set(words.map(w=>w.topic))].sort((a,b)=>a.localeCompare(b))}
function fillSelect(el,allText){const old=el.value;el.innerHTML=`<option value="all">${allText}</option>`+topics().map(t=>`<option>${esc(t)}</option>`).join('');if([...el.options].some(o=>o.value===old))el.value=old}
function esc(v=''){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function norm(v=''){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[.,!?;:]/g,'').replace(/\s+/g,' ').trim()}
function acceptable(input,answer){const a=norm(input),options=answer.split(/[,;/]|\bor\b/i).map(norm).filter(Boolean);return options.some(x=>a===x||a.length>3&&x.includes(a)||x.length>3&&a.includes(x))}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function renderAll(){fillSelect($('#reviewTopic'),'Tất cả chủ đề');fillSelect($('#filterTopic'),'Tất cả chủ đề');$('#topicSuggestions').innerHTML=topics().map(t=>`<option value="${esc(t)}">`).join('');renderTable();renderStats()}
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent={review:'Ôn luyện',vocabulary:'Kho từ vựng',stats:'Thống kê'}[name];$('.sidebar').classList.remove('open');if(name==='stats')renderStats()}
$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('.mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');
function filteredWords(){const q=norm($('#searchInput').value),topic=$('#filterTopic').value,level=$('#filterLevel').value;return words.filter(w=>(topic==='all'||w.topic===topic)&&(level==='all'||w.level===level)&&(!q||norm([w.english,w.vietnamese,w.example].join(' ')).includes(q)))}
function renderTable(){const list=filteredWords();$('#wordEmpty').classList.toggle('hidden',!!list.length);$('#wordTable').innerHTML=list.map(w=>`<tr><td><strong>${esc(w.english)}</strong><small>${esc(w.example||'Chưa có ví dụ')}</small></td><td>${esc(w.vietnamese)}</td><td>${esc(w.topic)}</td><td><span class="level-pill">${w.level}</span></td><td><span class="status-pill ${w.mastered?'learned':'new'}">${w.mastered?'Đã học':'Mới'}</span></td><td class="row-actions"><button data-edit="${w.id}" aria-label="Sửa">✎</button><button class="delete" data-delete="${w.id}" aria-label="Xóa">⌫</button></td></tr>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>openWord(Number(b.dataset.edit)));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteWord(Number(b.dataset.delete)))}
['input','change'].forEach(e=>{$('#searchInput').addEventListener(e,renderTable);$('#filterTopic').addEventListener(e,renderTable);$('#filterLevel').addEventListener(e,renderTable)});
function openWord(id){$('#wordForm').reset();$('#wordId').value='';$('#dialogTitle').textContent='Thêm từ mới';if(id){const w=words.find(x=>x.id===id);$('#wordId').value=w.id;$('#englishInput').value=w.english;$('#vietnameseInput').value=w.vietnamese;$('#topicInput').value=w.topic;$('#levelInput').value=w.level;$('#exampleInput').value=w.example||'';$('#dialogTitle').textContent='Sửa từ vựng'}$('#wordDialog').showModal()}
$('#addWordBtn').onclick=()=>openWord();
$$('[data-close-dialog]').forEach(b=>b.onclick=()=>$('#wordDialog').close());
$('#wordForm').addEventListener('submit',async e=>{e.preventDefault();const id=Number($('#wordId').value);const old=words.find(w=>w.id===id)||{};const data={...old,english:$('#englishInput').value.trim(),vietnamese:$('#vietnameseInput').value.trim(),topic:$('#topicInput').value.trim(),level:$('#levelInput').value,example:$('#exampleInput').value.trim(),mastered:old.mastered||false,correct:old.correct||0,attempts:old.attempts||0,createdAt:old.createdAt||Date.now()};if(id){data.id=id;await req(tx(WORDS,'readwrite').put(data))}else await req(tx(WORDS,'readwrite').add(data));$('#wordDialog').close();await load();toast(id?'Đã cập nhật từ vựng':'Đã thêm từ mới')});
async function deleteWord(id){if(!confirm('Xóa từ này khỏi danh sách?'))return;await req(tx(WORDS,'readwrite').delete(id));await load();toast('Đã xóa từ vựng')}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
$('#startReview').onclick=startReview;$('#reviewAgain').onclick=startReview;
function startReview(){const topic=$('#reviewTopic').value,level=$('#reviewLevel').value,direction=$('input[name="direction"]:checked').value;const deck=words.filter(w=>(topic==='all'||w.topic===topic)&&(level==='all'||w.level===level));if(!deck.length)return toast('Không có từ phù hợp với bộ lọc');session={topic,level,direction,total:deck.length,mastered:new Set(),queue:shuffle(deck.map(w=>w.id)),attempts:0};$('#quizEmpty').classList.add('hidden');$('#completion').classList.add('hidden');$('#quizContent').classList.remove('hidden');nextCard()}
function nextCard(){if(!session.queue.length)return finishReview();current=words.find(w=>w.id===session.queue.shift());answerLocked=false;$('#feedback').className='feedback hidden';$('#nextBtn').classList.add('hidden');$('#answerForm').classList.remove('hidden');$('#answerInput').value='';$('#answerInput').focus();$('#quizTopicBadge').textContent=current.topic;$('#quizLevelBadge').textContent=current.level;$('#quizCounter').textContent=`${session.mastered.size} / ${session.total}`;$('#quizProgress').style.width=`${session.mastered.size/session.total*100}%`;const en=session.direction==='en-vi';$('#quizLabel').textContent=en?'Nhập nghĩa tiếng Việt':'Nhập từ hoặc cụm từ tiếng Anh';$('#quizPrompt').textContent=en?current.english:current.vietnamese;$('#quizExample').textContent=en&&current.example?current.example:''}
$('#answerForm').addEventListener('submit',async e=>{e.preventDefault();if(answerLocked)return;answerLocked=true;const en=session.direction==='en-vi',expected=en?current.vietnamese:current.english,ok=acceptable($('#answerInput').value,expected);current.attempts=(current.attempts||0)+1;session.attempts++;if(ok){current.correct=(current.correct||0)+1;current.mastered=true;session.mastered.add(current.id);$('#feedback').className='feedback correct';$('#feedback').innerHTML=`Chính xác! <strong>${esc(current.english)}</strong> — ${esc(current.vietnamese)}`}else{session.queue.push(current.id);$('#feedback').className='feedback wrong';$('#feedback').innerHTML=`Chưa đúng. Đáp án: <strong>${esc(expected)}</strong>. Từ này sẽ xuất hiện lại.`}await req(tx(WORDS,'readwrite').put(current));$('#answerForm').classList.add('hidden');$('#nextBtn').classList.remove('hidden');$('#nextBtn').focus()});
$('#nextBtn').onclick=nextCard;$('#speakBtn').onclick=()=>speak(current?.english);function speak(text){if(!text||!('speechSynthesis'in window))return toast('Trình duyệt không hỗ trợ giọng đọc');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='en-US'&&/Google|Samantha|Microsoft|US/i.test(v.name))||voices.find(v=>v.lang==='en-US')||null;u.rate=.88;speechSynthesis.speak(u)}
async function finishReview(){for(const id of session.mastered){const w=words.find(x=>x.id===id);w.mastered=true;await req(tx(WORDS,'readwrite').put(w))}$('#quizContent').classList.add('hidden');$('#completion').classList.remove('hidden');$('#completionText').textContent=session.topic==='all'?`Bạn đã trả lời đúng toàn bộ ${session.total} từ trong lượt ôn này.`:`Chủ đề “${session.topic}” đã đạt 100% trong lượt ôn này.`;await load()}
function renderStats(){const total=words.length,learned=words.filter(w=>w.mastered).length;$('#totalWords').textContent=total;$('#learnedWords').textContent=learned;$('#masteryRate').textContent=total?Math.round(learned/total*100)+'%':'0%';const ts=topics().map(t=>{const arr=words.filter(w=>w.topic===t),done=arr.filter(w=>w.mastered).length;return{t,total:arr.length,done,p:arr.length?Math.round(done/arr.length*100):0}});$('#completedTopics').textContent=ts.filter(x=>x.p===100).length;const levels=['A1','A2','B1','B2','C1'],max=Math.max(1,...levels.map(l=>words.filter(w=>w.level===l).length));$('#levelChart').innerHTML=levels.map(l=>{const n=words.filter(w=>w.level===l).length;return`<div class="bar-row"><strong>${l}</strong><div class="bar-bg"><div class="bar-fill" style="width:${n/max*100}%"></div></div><span>${n}</span></div>`}).join('');$('#topicStats').innerHTML=ts.map(x=>`<div class="topic-row"><div class="topic-head"><strong>${esc(x.t)}</strong><span>${x.done}/${x.total} • ${x.p}%</span></div><div class="topic-progress"><span style="width:${x.p}%"></span></div></div>`).join('')||'<p>Chưa có dữ liệu.</p>'}
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),words},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='wordflow-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.words))throw Error();const store=tx(WORDS,'readwrite');await req(store.clear());for(const w of data.words){const copy={...w};delete copy.id;await req(tx(WORDS,'readwrite').add(copy))}await load();toast('Đã nhập dữ liệu thành công')}catch{toast('File dữ liệu không hợp lệ')}e.target.value=''};
db=await openDB();await load();
